import React from 'react';
import './ComponentPreview.css'; // Import the corresponding stylesheet

const ComponentPreview = ({ lessonPlan }) => {

  // // Function to render components based on type
  // const renderComponentPreview = (comp) => {
  //   // console.log("comp is:", comp)
  //   if (!comp) {
  //     return null;
  //   }

  //   switch (comp.type) {
  //     case 'Title':
  //     case 'Overview':
  //     case 'Audience':
  //       return (
  //         <>
  //           <div className="titleRow">
  //             <h3>{comp.type}</h3>
  //           </div>
  //           {comp.properties.title && <h4>{comp.properties.title}</h4>}
  //           <p>{comp.properties.value}</p>
  //         </>
  //       );
  //       case 'Objectives':
  //         return (
  //           <>
  //             <div className="titleRow">
  //               <h3>Learning {comp.type}</h3>
  //             </div>
  //             {comp.properties.title && <h4>{comp.properties.title}</h4>}
  //             <p>{comp.properties.value}</p>
  //           </>
  //         );
  //       case 'Activity':
  //         return (
  //           <>
  //             <div className="titleRow">
  //               <h3>{comp.type}: {comp.properties.title}</h3>
  //             </div>
  //             <h5>Description</h5>
  //             <p>{comp.properties.value}</p>
              
  //             {comp.properties.assessment && <h5>Assessment</h5>}
  //             {comp.properties.assessment && <p>{comp.properties.assessment}</p>}
  //           </>
  //         );
  //       case 'AIActivity':
  //         return (
  //           <>
  //             <div className="titleRow">
  //               <h3>AI Literacy Activity</h3>
  //             </div>
  //             <p>Duration: {comp.properties.value} minutes.</p>
  //             {comp.properties.req && <h5>Activity Specifications</h5>}
  //             {comp.properties.req && <p>{comp.properties.req}</p>}
  //           </>
  //         );
  //       case 'Custom':
  //         return (
  //           <>
  //             <div className="titleRow">
  //               <h3>{comp.properties.title}</h3>
  //             </div>
              
  //             <p>{comp.properties.value}</p>
  //           </>
  //         );
  //       case 'Duration':
  //         return (
  //           <>
  //             <div className="titleRow">
  //               <h3>{comp.type}</h3>
  //             </div>
  //             {comp.properties.title && <h4>{comp.properties.title}</h4>}
  //             <p>{comp.properties.value} minutes</p>
  //           </>
  //         );
  //     case 'AIObjectives':
  //       return (
  //         <>
  //           <div className="titleRow">
  //             <h3>AI Literacy Learning Objectives</h3>
  //           </div>
  //           <ul>
  //             {comp.properties.checklist.filter(item => item.checked).map((item, index) => (
  //               <li key={index}>{item.label}</li>
  //             ))}
  //             {comp.properties.customObjective && <li>{comp.properties.customObjective}</li>}
  //           </ul>
  //         </>
  //       );
  //     default:
  //       return <p>Unknown Component Type</p>;
  //   }
  // };

  const previewLessonPlan = (lessonPlan) => {
    if (!lessonPlan) {
      return null;
    }

    return (
      <>
      {/* Title */}
      {lessonPlan.title && <>
        <div className="titleRow">
              <h3>Lesson Title</h3>
        </div>
        <h4>{lessonPlan.title}</h4>
        </>}
      {/* Duration */}
      {lessonPlan.duration && <>
        <div className="titleRow">
                <h3>Duration</h3>
        </div>
        <h4>{lessonPlan.duration}</h4>
        <p> minutes</p>
      </>}
      {/* Overview */}
      {lessonPlan.overview && <>
        <div className="titleRow">
              <h3>Overview</h3>
        </div>
        <p>{lessonPlan.overview}</p>
        </>}
      {/* Audience */}
      {lessonPlan.audience && <>
        <div className="titleRow">
              <h3>Target Audience</h3> 
        </div>
        <p>{lessonPlan.audience}</p>
        </>}
      {/* Objectives */}
      {lessonPlan.objectives && <>
        <div className="titleRow">
              <h3>Learning Objectives</h3>
        </div>
        <p>{lessonPlan.objectives}</p>
        </>}
      {/* Activity */}
      {lessonPlan.activity.title && <>
        <div className="titleRow">
              <h3>Activity: {lessonPlan.activity.title}</h3>
        </div>
        {lessonPlan.activity.description && <><h5>Description</h5><p>{lessonPlan.activity.description}</p></>}
        {lessonPlan.activity.assessment && <><h5>Assessment</h5><p>This will be generated by the AI when you submit.</p></>}
        {lessonPlan.activity.alternatives &&  <><h5>Activity Alternatives</h5><p>This will be generated by the AI when you submit.</p></>}
        </>}
      {/* AI Literacy Objectives */}
        { (lessonPlan.ailitobjectives.some(item => item.checked) || lessonPlan.customobjective) && (
          <>
            <div className="titleRow">
              <h3>AI Literacy Learning Objectives</h3>
            </div>
            <ul>
              {lessonPlan.ailitobjectives.filter(item => item.checked).map((item, index) => (
                <li key={index}>{item.label}</li>
              ))}
              {lessonPlan.customobjective && <li>{lessonPlan.customobjective}</li>}
            </ul>
          </>
        )}
      {/* AI Literacy Activity */}
      {lessonPlan.aiactivity.duration && <>
        <div className="titleRow">
              <h3>AI Literacy Activity</h3>
        </div>
        <p>Duration: {lessonPlan.aiactivity.duration} minutes.</p>
        {lessonPlan.aiactivity.req && <><h5>Requirements/Specifications</h5><p>{lessonPlan.aiactivity.req}</p></>}
        {lessonPlan.aiactivity.assessment && <><h5>Assessment</h5><p>This will be generated by the AI when you submit.</p></>}
        {lessonPlan.aiactivity.alternatives &&  <><h5>Activity Alternatives</h5><p>This will be generated by the AI when you submit.</p></>}
        </>}

      </>
    );
  };

  return (
    <div className="componentPreview">
      {previewLessonPlan(lessonPlan)}
    </div>
  );
};

export default ComponentPreview;
